const bookAbbreviations = {
    // Antiguo Testamento
    'gn': 'genesis',
    'gen': 'genesis',
    'ex': 'exodo',
    'exo': 'exodo',
    'lv': 'levitico',
    'lev': 'levitico',
    'nm': 'numeros',
    'num': 'numeros',
    'dt': 'deuteronomio',
    'deu': 'deuteronomio',
    'jos': 'josue',
    'jue': 'jueces',
    'rt': 'rut',
    'rut': 'rut',
    '1s': '1_samuel',
    '1sam': '1_samuel',
    '2s': '2_samuel',
    '2sam': '2_samuel',
    '1r': '1_reyes',
    '1re': '1reyes',
    '2r': '2reyes',
    '2re': '2reyes',
    '1cr': '1_cronicas',
    '1cro': '1_cronicas',
    '2cr': '2_cronicas',
    '2cro': '2_cronicas',
    'esd': 'esdras',
    'neh': 'nehemias',
    'est': 'ester',
    'job': 'job',
    'sal': 'salmos',
    'pr': 'proverbios',
    'pro': 'proverbios',
    'ec': 'eclesiastes',
    'ecl': 'eclesiastes',
    'cnt': 'cantares',
    'can': 'cantares',
    'is': 'isaias',
    'isa': 'isaias',
    'jer': 'jeremias',
    'lm': 'lamentaciones',
    'lam': 'lamentaciones',
    'ez': 'ezequiel',
    'eze': 'ezequiel',
    'dn': 'daniel',
    'dan': 'daniel',
    'os': 'oseas',
    'ose': 'oseas',
    'jl': 'joel',
    'joe': 'joel',
    'am': 'amos',
    'amo': 'amos',
    'abd': 'abdias',
    'jon': 'jonas',
    'mi': 'miqueas',
    'miq': 'miqueas',
    'nah': 'nahum',
    'hab': 'habacuc',
    'sof': 'sofonias',
    'hag': 'hageo',
    'zac': 'zacarias',
    'mal': 'malaquias',
    
    // Nuevo Testamento
    'mt': 'mateo',
    'mat': 'mateo',
    'mr': 'marcos',
    'mar': 'marcos',
    'lc': 'lucas',
    'luc': 'lucas',
    'jn': 'juan',
    'jua': 'juan',
    'hch': 'hechos',
    'hec': 'hechos',
    'ro': 'romanos',
    'rom': 'romanos',
    '1co': '1_corintios',
    '1cor': '1_corintios',
    '2co': '2_corintios',
    '2cor': '2_corintios',
    'ga': 'galatas',
    'gal': 'galatas',
    'ef': 'efesios',
    'efe': 'efesios',
    'fil': 'filipenses',
    'flp': 'filipenses',
    'col': 'colosenses',
    '1ts': '1_tesalonicenses',
    '1te': '1_tesalonicenses',
    '2ts': '2_tesalonicenses',
    '2te': '2_tesalonicenses',
    '1ti': '1_timoteo',
    '1tim': '1_timoteo',
    '2ti': '2_timoteo',
    '2tim': '2_timoteo',
    'tit': 'tito',
    'flm': 'filemon',
    'heb': 'hebreos',
    'stg': 'santiago',
    'sant': 'santiago',
    '1p': '1_pedro',
    '1pe': '1_pedro',
    '2p': '2_pedro',
    '2pe': '2_pedro',
    '1jn': '1_juan',
    '1ju': '1_juan',
    '2jn': '2_juan',
    '2ju': '2_juan',
    '3jn': '3_juan',
    '3ju': '3_juan',
    'jud': 'judas',
    'ap': 'apocalipsis',
    'apo': 'apocalipsis'
};

const getBookFileName = (bookInput) => {
    const normalizedInput = bookInput.toLowerCase().trim();
    
    // Si es una abreviación, devolver el nombre del archivo
    if (bookAbbreviations[normalizedInput]) {
        return bookAbbreviations[normalizedInput];
    }
    
    // Si no es una abreviación, asumir que es el nombre completo
    return normalizedInput;
};

export default {getBookFileName};